# -*- coding: utf-8 -*-
"""mapeamento_eficiencia_hidrica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhqtqN6s3Yj528kmRydfVRxWEHg8Qp1k
"""

#LIMPAR DADOS BRUTOS


import pandas as pd

def limpar_planilha_wfn(caminho_arquivo, linha_inicio, col_produto, col_tipo_agua, col_valor_alvo):
    """
    Função para ler e limpar as planilhas brutas da Water Footprint Network.
    """
    print(f"Processando arquivo: {caminho_arquivo}...")

    # 1. Carrega o arquivo ignorando os cabeçalhos complexos
    # header=None força o pandas a tratar as colunas como números (0, 1, 2, 3...)
    df_raw = pd.read_excel(caminho_arquivo, header=None, skiprows=linha_inicio)

    # 2. Isola apenas as 3 colunas que importam
    df = df_raw[[col_produto, col_tipo_agua, col_valor_alvo]].copy()
    df.columns = ['Produto', 'Tipo_Agua', 'Valor']

    # 3. Limpeza de texto para evitar erros de digitação ocultos no Excel
    df['Tipo_Agua'] = df['Tipo_Agua'].astype(str).str.strip().str.capitalize()
    df['Produto'] = df['Produto'].astype(str).str.strip()

    # Transforma strings vazias ou 'nan' em valores nulos reais do Pandas
    df.loc[df['Produto'] == 'nan', 'Produto'] = None
    df.loc[df['Produto'] == '', 'Produto'] = None

    # 4. O PULO DO GATO: Forward Fill (ffill)
    # Preenche os nomes de produtos vazios com o nome do produto da linha de cima
    df['Produto'] = df['Produto'].ffill()

    # 5. Filtra apenas as linhas que contêm os dados de água
    df = df[df['Tipo_Agua'].isin(['Green', 'Blue', 'Grey'])]

    # Converte a coluna de valores para números (transforma erros ou hífens em NaN)
    df['Valor'] = pd.to_numeric(df['Valor'], errors='coerce').fillna(0)

    # 6. Dinâmica de Tabela (Pivot)
    # Transforma as linhas Green, Blue e Grey em colunas
    df_clean = df.pivot_table(
        index='Produto',
        columns='Tipo_Agua',
        values='Valor',
        aggfunc='first'
    ).reset_index()

    # 7. Formatação Final
    df_clean.columns.name = None # Remove o nome do índice do pivot

    # Garante que todas as colunas existam mesmo se faltar algum dado
    for cor in ['Green', 'Blue', 'Grey']:
        if cor not in df_clean.columns:
            df_clean[cor] = 0.0

    df_clean = df_clean.rename(columns={
        'Produto': 'Produto_EN',
        'Green': 'Agua_Verde',
        'Blue': 'Agua_Azul',
        'Grey': 'Agua_Cinza'
    })

    # Cria a coluna final de totalização
    df_clean['Agua_Total_m3_t'] = df_clean['Agua_Verde'] + df_clean['Agua_Azul'] + df_clean['Agua_Cinza']

    print(f"Sucesso! {len(df_clean)} produtos extraídos.")
    return df_clean[['Produto_EN', 'Agua_Verde', 'Agua_Azul', 'Agua_Cinza', 'Agua_Total_m3_t']]

# ==========================================
# COMO EXECUTAR (Ajuste os índices abaixo)
# ==========================================

try:
    df_animais = limpar_planilha_wfn(
        caminho_arquivo='Report48-Appendix-V.xlsx', # Nome do seu arquivo baixado
        linha_inicio=4,       # Pula as primeiras 4 linhas de cabeçalho bagunçado
        col_produto=2,        # Índice da coluna com o nome do produto
        col_tipo_agua=8,      # Índice da coluna que tem as palavras Green/Blue/Grey
        col_valor_alvo=12     # Índice da coluna com os valores (ex: Média Global)
    )

    # Exporta o resultado limpo
    df_animais.to_excel('waterstat_animais_limpo.xlsx', index=False)
    print("\nVisualização dos dados limpos:")
    print(df_animais.head())

except Exception as e:
    print(f"Erro ao processar: {e}")

import pandas as pd

def limpar_planilha_vegetais(caminho_arquivo, linha_inicio, col_produto, col_tipo_agua, col_valor_alvo):
    """
    Função dedicada para limpar o Apêndice II (Report 47) da Water Footprint Network.
    """
    print(f"Lendo o arquivo: {caminho_arquivo}...")

    # Carrega o Excel ignorando o cabeçalho complexo
    df_raw = pd.read_excel(caminho_arquivo, header=None, skiprows=linha_inicio)

    # Filtra apenas as 3 colunas necessárias
    df = df_raw[[col_produto, col_tipo_agua, col_valor_alvo]].copy()
    df.columns = ['Produto', 'Tipo_Agua', 'Valor']

    # Limpeza de espaços em branco e padronização
    df['Tipo_Agua'] = df['Tipo_Agua'].astype(str).str.strip().str.capitalize()
    df['Produto'] = df['Produto'].astype(str).str.strip()

    # Substitui células que o Pandas leu como 'nan' por valores nulos reais
    df.loc[df['Produto'] == 'nan', 'Produto'] = None
    df.loc[df['Produto'] == '', 'Produto'] = None

    # PREENCHIMENTO PARA BAIXO (O segredo para ler essa tabela)
    # Copia o nome do alimento (ex: Wheat) para as linhas do Blue e Grey
    df['Produto'] = df['Produto'].ffill()

    # Mantém apenas as linhas que informam a cor da água
    df = df[df['Tipo_Agua'].isin(['Green', 'Blue', 'Grey'])]

    # Converte os valores para números (erros ou hífens viram zero)
    df['Valor'] = pd.to_numeric(df['Valor'], errors='coerce').fillna(0)

    # Transforma as cores da água em colunas (Pivot)
    df_clean = df.pivot_table(
        index='Produto',
        columns='Tipo_Agua',
        values='Valor',
        aggfunc='first'
    ).reset_index()

    df_clean.columns.name = None # Limpa o nome do índice

    # Garante que as três colunas de água existam
    for cor in ['Green', 'Blue', 'Grey']:
        if cor not in df_clean.columns:
            df_clean[cor] = 0.0

    # Renomeia para o padrão que o nosso script principal (Rapidfuzz) exige
    df_clean = df_clean.rename(columns={
        'Produto': 'Produto_EN',
        'Green': 'Agua_Verde',
        'Blue': 'Agua_Azul',
        'Grey': 'Agua_Cinza'
    })

    # Calcula a Pegada Hídrica Total
    df_clean['Agua_Total_m3_t'] = df_clean['Agua_Verde'] + df_clean['Agua_Azul'] + df_clean['Agua_Cinza']

    print(f"Sucesso! {len(df_clean)} matrizes vegetais extraídas.")
    return df_clean[['Produto_EN', 'Agua_Verde', 'Agua_Azul', 'Agua_Cinza', 'Agua_Total_m3_t']]


# ==========================================
# EXECUÇÃO PARA O REPORT 47 (VEGETAIS) - MÉDIA GLOBAL
# ==========================================
try:
    df_vegetais = limpar_planilha_vegetais(
        caminho_arquivo='Report47-Appendix-II.xlsx',
        linha_inicio=6,       # Pula as 6 linhas de cabeçalho. O dado começa na 7ª linha do Excel
        col_produto=4,        # Coluna E: Nome curto (Product description FAOSTAT)
        col_tipo_agua=8,      # Coluna I: WF type (Green/Blue/Grey)
        col_valor_alvo=9      # Coluna J: Global average (Média Mundial)
    )

    # Exporta para ser usado na etapa final do artigo
    df_vegetais.to_excel('waterstat_vegetais_global_limpo.xlsx', index=False)
    print("\nVisualização dos primeiros dados limpos:")
    print(df_vegetais.head())

except Exception as e:
    print(f"Erro na extração: {e}")

!pip install deep_translator

import pandas as pd
from deep_translator import GoogleTranslator
from tqdm import tqdm

tqdm.pandas(desc="Traduzindo a TACO para o Inglês")

def preparar_taco(caminho_arquivo_entrada, caminho_arquivo_saida):
    print("Carregando a base da TACO...")
    df = pd.read_excel(caminho_arquivo_entrada)

    # ==========================================
    # O FIX INDESTRUTÍVEL (BUSCA DINÂMICA + POSIÇÃO)
    # ==========================================
    col_nome = None
    col_prot = None

    # 1. Tenta achar pelo nome (mesmo que esteja escrito apenas "alimento" ou "Proteína")
    for col in df.columns:
        if 'alimento' in str(col).lower() or 'descri' in str(col).lower():
            col_nome = col
        if 'rote' in str(col).lower(): # Pega "Proteína", "Proteina", "proteina"
            col_prot = col

    # 2. Se o cabeçalho estiver tão destruído que não achou as palavras, apela para a posição!
    # Na TACO padrão, a coluna 1 (2ª coluna) é o nome e a coluna 5 (6ª coluna) é a proteína.
    if not col_nome:
        col_nome = df.columns[1]
    if not col_prot:
        col_prot = df.columns[5]

    print(f"-> Coluna identificada para o NOME: '{col_nome}'")
    print(f"-> Coluna identificada para a PROTEÍNA: '{col_prot}'")

    # Renomeia as colunas com segurança
    df = df.rename(columns={
        col_nome: 'Produto_PT',
        col_prot: 'Proteina_g'
    })

    # ==========================================
    # CONTINUAÇÃO DO PROCESSAMENTO
    # ==========================================
    # Converte vírgula para ponto e transforma textos (como "Tr" de traços) em nulo
    if df['Proteina_g'].dtype == object:
        df['Proteina_g'] = df['Proteina_g'].astype(str).str.replace(',', '.')
        df['Proteina_g'] = pd.to_numeric(df['Proteina_g'], errors='coerce')

    # Aplica a regra da Anvisa (>= 6g)
    df_fonte_proteina = df[df['Proteina_g'] >= 6.0].copy()
    print(f"\nAlimentos que são fonte de proteína (>=6g) encontrados: {len(df_fonte_proteina)}")

    # Inicia a tradução
    tradutor = GoogleTranslator(source='pt', target='en')

    df_fonte_proteina['Produto_EN'] = df_fonte_proteina['Produto_PT'].progress_apply(
        lambda texto: tradutor.translate(str(texto)) if pd.notna(texto) else None
    )

    # Injeta a coluna para a tabela DIAAS
    df_fonte_proteina['Categoria_Alimento'] = ""

    # Organiza a saída
    colunas_finais = ['Produto_PT', 'Produto_EN', 'Categoria_Alimento', 'Proteina_g']
    outras_colunas = [col for col in df_fonte_proteina.columns if col not in colunas_finais]

    df_final = df_fonte_proteina[colunas_finais + outras_colunas]

    # Salva o arquivo final
    df_final.to_excel(caminho_arquivo_saida, index=False)
    print(f"\nSucesso! Arquivo salvo como: {caminho_arquivo_saida}")

# Execução
try:
    preparar_taco('taco.xlsx', 'taco_traduzida.xlsx')
except Exception as e:
    print(f"Ocorreu um erro crítico: {e}")

!pip install rapidfuzz

!pip install rapidfuzz

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util
import torch

# ================================
# 1. CARREGAR OS ARQUIVOS EXCEL E LIMPAR
# ================================
print("Carregando bases de dados...")
taco = pd.read_excel('taco_traduzida.xlsx')
diaas = pd.read_excel('Tabela DIAAS.xlsx')
wf_animais = pd.read_excel('waterstat_animais_limpo.xlsx')
wf_vegetais = pd.read_excel('waterstat_vegetais_limpo.xlsx')

pegada_global = pd.concat([wf_animais, wf_vegetais], ignore_index=True).dropna(subset=['Produto_EN'])
pegada_choices = pegada_global['Produto_EN'].tolist()

taco['Produto_EN'] = taco['Produto_EN'].fillna("").astype(str)
taco['Produto_PT_limpo'] = taco['Produto_PT'].fillna("").astype(str).str.lower()

# ================================
# 2. ANCORAGEM OBRIGATÓRIA (REGRAS RÍGIDAS)
# ================================
# Dicionário mapeando a palavra em PT para a Categoria Mãe exata da WFN
regras_ouro = {
    'carne, bovina': 'Bovine cuts boneless, fresh or chilled',
    'hamburguer': 'Bovine cuts boneless, fresh or chilled',
    'linguica, frango': 'Meat of fowls of the species Gallus domesticus', # Tem que vir antes da regra de 'frango' e 'linguica' geral
    'frango': 'Meat of fowls of the species Gallus domesticus',
    'peru': 'Turkey meat and meat offal prepared or preserved, excluding livers',
    'porco': 'Hams, shoulders and cuts thereof, of swine bone in, fresh or chilled',
    'linguica': 'Swine meat cured, nes',
    'presunto': 'Swine meat cured, nes',
    'leite, de vaca, desnatado': 'Milk powder not exceeding 1.5% fat',
    'leite, de vaca, integral': 'Milk and cream not concentrated and unsweetened exceeding 6% fat',
    'leite, condensado': 'Milk and cream nes sweetened',
    'queijo': 'Cheese nes',
    'ovo': 'Eggs, bird, in shell, fresh, preserved or cooked',
    'arroz': 'Rice, paddy',
    'feijao': 'Beans, dry',
    'trigo': 'Wheat',
    'macarrao': 'Wheat',
    'pao': 'Wheat',
    'aveia': 'Oats',
    'milho': 'Maize',
    'soja': 'Soybeans'
}

print("Aplicando ancoragem rígida para carnes e grãos base...")
taco['Match_WF_Rigido'] = None

for i, row in taco.iterrows():
    nome_pt = row['Produto_PT_limpo']
    for chave_pt, valor_wfn in regras_ouro.items():
        if chave_pt in nome_pt:
            taco.at[i, 'Match_WF_Rigido'] = valor_wfn
            break # Achou a regra, para de procurar

# ================================
# 3. VETORIZAÇÃO SEMÂNTICA (Apenas para os "difíceis")
# ================================
print("Carregando o modelo de IA para analisar os alimentos restantes...")
modelo = SentenceTransformer('all-MiniLM-L6-v2')
embeddings_wfn = modelo.encode(pegada_choices, convert_to_tensor=True)

print("Calculando IA Semântica...")
for i, row in taco.iterrows():
    # Se já foi resolvido pela regra rígida, pula o cálculo da IA e dá Score 100%
    if pd.notna(row['Match_WF_Rigido']):
        taco.at[i, 'Match_Final_WFN'] = row['Match_WF_Rigido']
        taco.at[i, 'Score_Confianca'] = 100.0
    else:
        # Se não tem regra, a IA vetorial entra em ação
        embedding_query = modelo.encode(row['Produto_EN'], convert_to_tensor=True)
        cos_score = util.cos_sim(embedding_query, embeddings_wfn)[0]

        melhor_idx = torch.argmax(cos_score).item()
        melhor_score = cos_score[melhor_idx].item() * 100

        taco.at[i, 'Match_Final_WFN'] = pegada_choices[melhor_idx]
        taco.at[i, 'Score_Confianca'] = round(melhor_score, 2)

# ================================
# 4. EXPORTAR TABELA DE REVISÃO E APLICAR MATCH DE PESCADOS
# ================================
# Limpa Pescados que a IA tentou adivinhar (Pescados não têm pegada hídrica medida pela WFN)
palavras_peixe = ['pescada', 'salmao', 'sardinha', 'lambari', 'abadejo', 'atum', 'bacalhau', 'cacao', 'camarao', 'caranguejo', 'corimba', 'corvina', 'dourada', 'manjuba', 'merluza', 'pintado', 'porquinho', 'tucunare']
for i, row in taco.iterrows():
    if any(peixe in row['Produto_PT_limpo'] for peixe in palavras_peixe):
        taco.at[i, 'Match_Final_WFN'] = None
        taco.at[i, 'Score_Confianca'] = 0.0

correspondencias = taco[['Produto_PT', 'Produto_EN', 'Match_Final_WFN', 'Score_Confianca']].sort_values(by='Score_Confianca', ascending=True)
correspondencias.to_excel('1_revisao_hibrida.xlsx', index=False)
print("Tabela de revisão gerada: '1_revisao_hibrida.xlsx'")

# ================================
# 5. MERGE MÚLTIPLO: TACO + PEGADA + DIAAS
# ================================
print("Realizando os cruzamentos de dados finais...")
df = pd.merge(taco, pegada_global, left_on='Match_Final_WFN', right_on='Produto_EN', how='inner')

df['Categoria_Alimento'] = df['Categoria_Alimento'].astype(str).str.strip()
diaas['Categoria_Alimento'] = diaas['Categoria_Alimento'].astype(str).str.strip()
df = pd.merge(df, diaas, on='Categoria_Alimento', how='left')
df['DIAAS'] = pd.to_numeric(df['DIAAS'], errors='coerce').fillna(50.0)

# ================================
# 6. CÁLCULO DAS EFICIÊNCIAS E EXPORTAÇÃO
# ================================
df['Proteina_g'] = pd.to_numeric(df['Proteina_g'], errors='coerce')
df['Agua_Total_m3_t'] = pd.to_numeric(df['Agua_Total_m3_t'], errors='coerce')
df = df.dropna(subset=['Proteina_g', 'Agua_Total_m3_t'])

df['Eficiencia_Bruta_g_m3'] = df['Proteina_g'] / df['Agua_Total_m3_t']
df['Proteina_Digestivel_g'] = df['Proteina_g'] * (df['DIAAS'] / 100)
df['Eficiencia_Real_g_m3'] = df['Proteina_Digestivel_g'] / df['Agua_Total_m3_t']

colunas_finais = [
    'Produto_PT', 'Match_Final_WFN', 'Score_Confianca', 'Categoria_Alimento',
    'Proteina_g', 'DIAAS', 'Proteina_Digestivel_g',
    'Agua_Verde', 'Agua_Azul', 'Agua_Cinza', 'Agua_Total_m3_t',
    'Eficiencia_Bruta_g_m3', 'Eficiencia_Real_g_m3'
]

df_final = df[colunas_finais].sort_values(by='Eficiencia_Real_g_m3', ascending=False)
df_final.to_excel('2_eficiencia_proteica_real_hibrida.xlsx', index=False)
print(f"\nSucesso! Arquivo final gerado: '2_eficiencia_proteica_real_hibrida.xlsx'")

import pandas as pd
from rapidfuzz import process, fuzz

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ==========================================
# 1. CONFIGURAÇÕES INICIAIS DE ESTILO
# ==========================================
# Estilo limpo e acadêmico para os gráficos
sns.set_theme(style="whitegrid")
plt.rcParams.update({'figure.autolayout': True}) # Evita que textos sejam cortados

print("Carregando os dados para os gráficos...")
# Lê o arquivo gerado no script anterior
df = pd.read_excel('2_eficiencia_proteica_real_hibrida.xlsx')

# Para gráficos de barras, vamos pegar os Top 20 alimentos mais eficientes
# Se tentar plotar os 250 de uma vez, os nomes ficam ilegíveis
df_top20 = df.head(20).copy()

# Encurtar nomes muito grandes para não poluir o eixo Y
df_top20['Produto_Curto'] = df_top20['Produto_PT'].apply(lambda x: str(x)[:30] + '...' if len(str(x)) > 30 else str(x))

# ==========================================
# GRÁFICO 1: PEGADA HÍDRICA EMPILHADA (Verde, Azul e Cinza)
# ==========================================
print("Gerando Gráfico 1: Pegada Hídrica Empilhada...")
fig1, ax1 = plt.subplots(figsize=(10, 8))

# Preparando os dados para o empilhamento
barras_dados = df_top20.set_index('Produto_Curto')[['Agua_Verde', 'Agua_Azul', 'Agua_Cinza']]

# Cores intuitivas: Verde para chuva, Azul para irrigação, Cinza escuro para poluição
cores = ['#2ca02c', '#1f77b4', '#7f7f7f']

barras_dados.plot(kind='barh', stacked=True, color=cores, ax=ax1, width=0.75)

ax1.set_title('Composição da Pegada Hídrica - Top 20 Alimentos Mais Eficientes', fontsize=14, pad=15)
ax1.set_xlabel('Pegada Hídrica Total (m³/tonelada)', fontsize=12)
ax1.set_ylabel('Matriz Alimentar', fontsize=12)
ax1.legend(['Água Verde (Chuva)', 'Água Azul (Irrigação/Rios)', 'Água Cinza (Poluição)'], title="Tipo de Água")
ax1.invert_yaxis() # Inverte para o #1 ficar no topo

plt.savefig('grafico1_pegada_empilhada.png', dpi=300, bbox_inches='tight')
plt.close()

# ==========================================
# GRÁFICO 2: DISPERSÃO (Scatter Plot) - O Quadrante da Sustentabilidade
# ==========================================
print("Gerando Gráfico 2: Dispersão (Água x Proteína)...")
fig2, ax2 = plt.subplots(figsize=(10, 8))

# Vamos plotar a base inteira aqui para mostrar a nuvem de dados
sns.scatterplot(
    data=df,
    x='Agua_Total_m3_t',
    y='Proteina_Digestivel_g',
    hue='Categoria_Alimento', # Pinta cada ponto com a cor da sua categoria
    palette='tab20',
    s=80, # Tamanho dos pontos
    alpha=0.8,
    ax=ax2
)

ax2.set_title('Relação entre Impacto Hídrico e Entrega de Proteína Digestível', fontsize=14, pad=15)
ax2.set_xlabel('Pegada Hídrica Total (m³/ton)', fontsize=12)
ax2.set_ylabel('Proteína Digestível (g/100g) - Ajustada pelo DIAAS', fontsize=12)

# Adiciona um texto explicativo no gráfico indicando onde está o "cenário ideal"
ax2.text(
    0.05, 0.95,
    'Cenário Ideal:\nAlta Proteína, Baixa Água',
    transform=ax2.transAxes,
    fontsize=11,
    verticalalignment='top',
    bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5)
)

# Coloca a legenda fora do gráfico para não tampar os pontos
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Categoria do Alimento")

plt.savefig('grafico2_dispersao.png', dpi=300, bbox_inches='tight')
plt.close()

# ==========================================
# GRÁFICO 3: CHOQUE DE REALIDADE (Eficiência Bruta vs Eficiência Real)
# ==========================================
print("Gerando Gráfico 3: Comparação de Eficiências (Bruta x Real)...")
fig3, ax3 = plt.subplots(figsize=(10, 8))

# Pegamos os 15 melhores para ficar com um visual de barras agrupadas perfeito
df_top15 = df.head(15).copy()
df_top15['Produto_Curto'] = df_top15['Produto_PT'].apply(lambda x: str(x)[:25] + '...' if len(str(x)) > 25 else str(x))

dados_comp = df_top15.set_index('Produto_Curto')[['Eficiencia_Bruta_g_m3', 'Eficiencia_Real_g_m3']]

# Plota barras lado a lado
dados_comp.plot(kind='barh', ax=ax3, color=['#ff7f0e', '#1f77b4'], width=0.8)

ax3.set_title('Impacto do Ajuste de Digestibilidade (DIAAS) na Eficiência', fontsize=14, pad=15)
ax3.set_xlabel('Eficiência Hídrica (g de proteína por m³ de água)', fontsize=12)
ax3.set_ylabel('Matriz Alimentar', fontsize=12)
ax3.legend(['Eficiência Bruta (Sem Ajuste)', 'Eficiência Real (Ajustada pelo DIAAS)'])
ax3.invert_yaxis()

plt.savefig('grafico3_eficiencia_comparada.png', dpi=300, bbox_inches='tight')
plt.close()

print("\nSucesso! 3 gráficos em alta resolução (300 DPI) foram salvos na sua pasta.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ==========================================
# 1. CONFIGURAÇÕES INICIAIS DE ESTILO
# ==========================================
sns.set_theme(style="whitegrid")
plt.rcParams.update({'figure.autolayout': True})

print("Carregando os dados para os novos gráficos...")
df = pd.read_excel('2_eficiencia_proteica_real_hibrida.xlsx')

# ==========================================
# GRÁFICO 4: OS MAIORES TEORES PROTEICOS (A Volta da Carne)
# ==========================================
print("Gerando Gráfico 4: Top 20 Alimentos com Mais Proteína Bruta...")
fig4, ax4 = plt.subplots(figsize=(10, 8))

# Ordena os alimentos estritamente pela quantidade de proteína (independente da água)
df_top_prot = df.sort_values(by='Proteina_g', ascending=False).head(20).copy()
df_top_prot['Produto_Curto'] = df_top_prot['Produto_PT'].apply(lambda x: str(x)[:25] + '...' if len(str(x)) > 25 else str(x))

dados_prot = df_top_prot.set_index('Produto_Curto')[['Proteina_g', 'Proteina_Digestivel_g']]

# Gráfico de barras lado a lado mostrando o que é bruto e o que é realmente absorvido
dados_prot.plot(kind='barh', ax=ax4, color=['#d62728', '#2ca02c'], width=0.8)

ax4.set_title('Top 20 Fontes de Proteína e a Retenção pelo DIAAS', fontsize=14, pad=15)
ax4.set_xlabel('Quantidade de Proteína (g/100g)', fontsize=12)
ax4.set_ylabel('Matriz Alimentar', fontsize=12)
ax4.legend(['Proteína Bruta', 'Proteína Digestível (Ajustada)'])
ax4.invert_yaxis()

plt.savefig('grafico4_top_proteinas.png', dpi=300, bbox_inches='tight')
plt.close()

# ==========================================
# GRÁFICO 5: ANÁLISE MACRO POR CATEGORIA (Eixos Duplos)
# ==========================================
print("Gerando Gráfico 5: Médias por Categoria (Eixos Combinados)...")
fig5, ax5a = plt.subplots(figsize=(12, 7))

# Calcula a média de água e proteína por categoria
df_cat = df.groupby('Categoria_Alimento').agg({
    'Agua_Total_m3_t': 'mean',
    'Proteina_Digestivel_g': 'mean'
}).reset_index().sort_values(by='Agua_Total_m3_t', ascending=True)

# Eixo esquerdo: Gráfico de Barras para a Pegada Hídrica Média
sns.barplot(data=df_cat, x='Categoria_Alimento', y='Agua_Total_m3_t', ax=ax5a, color='#1f77b4', alpha=0.7)
ax5a.set_ylabel('Pegada Hídrica Total Média (m³/ton)', color='#1f77b4', fontsize=12)
ax5a.tick_params(axis='y', labelcolor='#1f77b4')
ax5a.set_xlabel('Categoria do Alimento', fontsize=12)
ax5a.set_xticklabels(ax5a.get_xticklabels(), rotation=45, ha='right')

# Eixo direito: Gráfico de Linha para a Proteína Digestível Média
ax5b = ax5a.twinx()
sns.lineplot(data=df_cat, x='Categoria_Alimento', y='Proteina_Digestivel_g', ax=ax5b, color='#d62728', marker='o', linewidth=2.5, markersize=8)
ax5b.set_ylabel('Proteína Digestível Média (g/100g)', color='#d62728', fontsize=12)
ax5b.tick_params(axis='y', labelcolor='#d62728')

plt.title('Trade-off por Categoria: Custo Hídrico (Barras) vs. Entrega Nutricional (Linha)', fontsize=14, pad=15)

plt.savefig('grafico5_categorias_eixos_duplos.png', dpi=300, bbox_inches='tight')
plt.close()

# ==========================================
# GRÁFICO 6: BOLHAS MULTIDIMENSIONAIS (O Panorama Completo)
# ==========================================
print("Gerando Gráfico 6: Gráfico de Bolhas (4 Dimensões)...")
fig6, ax6 = plt.subplots(figsize=(12, 9))

# X = Água, Y = Proteína, Tamanho da Bolha = Eficiência Real, Cor = Categoria
# Filtramos outliers extremos de água (como especiarias) se houver, para não amassar o gráfico
df_bubble = df[df['Agua_Total_m3_t'] < df['Agua_Total_m3_t'].quantile(0.95)]

scatter = sns.scatterplot(
    data=df_bubble,
    x='Agua_Total_m3_t',
    y='Proteina_Digestivel_g',
    size='Eficiencia_Real_g_m3',
    sizes=(50, 800), # Ajusta o tamanho mínimo e máximo das bolhas
    hue='Categoria_Alimento',
    palette='Set2',
    alpha=0.7,
    edgecolor='black',
    ax=ax6
)

ax6.set_title('Panorama de Sustentabilidade: Água x Proteína x Eficiência Real', fontsize=14, pad=15)
ax6.set_xlabel('Custo Ambiental: Pegada Hídrica Total (m³/ton)', fontsize=12)
ax6.set_ylabel('Entrega Nutricional: Proteína Digestível (g/100g)', fontsize=12)

# Organiza as legendas fora do gráfico
h, l = scatter.get_legend_handles_labels()
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0)

plt.savefig('grafico6_bolhas_multidimensionais.png', dpi=300, bbox_inches='tight')
plt.close()

print("\nSucesso! Os 3 novos gráficos exploratórios foram gerados.")

# ================================
# 1. Carregar arquivos Excel
# ================================
taco = pd.read_excel('taco.xlsx')
pegada = pd.read_excel('pegada.xlsx')

# ================================
# 2. Renomear colunas para consistência
# ================================
taco = taco[['alimento', 'Proteína']].rename(columns={'alimento': 'Produto', 'Proteína': 'Proteina_g'})
pegada = pegada[['Produto', 'Total']].rename(columns={'Total': 'Agua_m3_t'})

# ================================
# 3. Função de correspondência aproximada
# ================================
def match_product(product, choices, threshold=80):
    """
    Encontra a melhor correspondência aproximada para 'product' dentro de 'choices'.
    Retorna None se nenhuma correspondência passar o threshold.
    """
    result = process.extractOne(product, choices, scorer=fuzz.token_sort_ratio)
    if result is not None:
        match, score, _ = result
        if score >= threshold:
            return match
    return None

# ================================
# 4. Criar lista de correspondências
# ================================
taco_choices = taco['Produto'].tolist()
pegada['Produto_correspondente'] = pegada['Produto'].apply(lambda x: match_product(x, taco_choices, threshold=60))

# ================================
# 5. Criar tabela de correspondência sugerida para revisão
# ================================
correspondencias = pegada[['Produto', 'Produto_correspondente']]
correspondencias.to_excel('correspondencias_sugeridas.xlsx', index=False)
print("Tabela de correspondência sugerida criada: 'correspondencias_sugeridas.xlsx'")

# ================================
# 6. Merge com tabela de pegada hídrica
# ================================
df = pd.merge(
    pegada,
    taco,
    left_on='Produto_correspondente',
    right_on='Produto',
    how='inner'
)


# ================================
# 7. Converter colunas para numérico e remover linhas inválidas
# ================================
df['Proteina_g'] = pd.to_numeric(df['Proteina_g'], errors='coerce')
df['Agua_m3_t'] = pd.to_numeric(df['Agua_m3_t'], errors='coerce')
df = df.dropna(subset=['Proteina_g', 'Agua_m3_t'])

# ================================
# 8. Calcular eficiência hídrica da proteína
# ================================
df['Proteina_por_m3'] = df['Proteina_g'] / df['Agua_m3_t']

# ================================
# 9. Ordenar por eficiência
# ================================
df_sorted = df.sort_values(by='Proteina_por_m3', ascending=False)

# ================================
# 10. Salvar resultado final
# ================================
df_sorted.to_excel('eficiencia_proteica_final_60.xlsx', index=False)
print("Arquivo final de eficiência hídrica criado: 'eficiencia_proteica_final_60.xlsx'")

# ================================
# 11. Mostrar top 10 alimentos mais eficientes
# ================================
print(df_sorted.head(10))

