# -*- coding: utf-8 -*-
"""mapeamento_eficiencia_hidrica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhqtqN6s3Yj528kmRydfVRxWEHg8Qp1k
"""

#LIMPAR DADOS BRUTOS


import pandas as pd

def limpar_planilha_wfn(caminho_arquivo, linha_inicio, col_produto, col_tipo_agua, col_valor_alvo):
    """
    Função para ler e limpar as planilhas brutas da Water Footprint Network.
    """
    print(f"Processando arquivo: {caminho_arquivo}...")

    # 1. Carrega o arquivo ignorando os cabeçalhos complexos
    # header=None força o pandas a tratar as colunas como números (0, 1, 2, 3...)
    df_raw = pd.read_excel(caminho_arquivo, header=None, skiprows=linha_inicio)

    # 2. Isola apenas as 3 colunas que importam
    df = df_raw[[col_produto, col_tipo_agua, col_valor_alvo]].copy()
    df.columns = ['Produto', 'Tipo_Agua', 'Valor']

    # 3. Limpeza de texto para evitar erros de digitação ocultos no Excel
    df['Tipo_Agua'] = df['Tipo_Agua'].astype(str).str.strip().str.capitalize()
    df['Produto'] = df['Produto'].astype(str).str.strip()

    # Transforma strings vazias ou 'nan' em valores nulos reais do Pandas
    df.loc[df['Produto'] == 'nan', 'Produto'] = None
    df.loc[df['Produto'] == '', 'Produto'] = None

    # 4. O PULO DO GATO: Forward Fill (ffill)
    # Preenche os nomes de produtos vazios com o nome do produto da linha de cima
    df['Produto'] = df['Produto'].ffill()

    # 5. Filtra apenas as linhas que contêm os dados de água
    df = df[df['Tipo_Agua'].isin(['Green', 'Blue', 'Grey'])]

    # Converte a coluna de valores para números (transforma erros ou hífens em NaN)
    df['Valor'] = pd.to_numeric(df['Valor'], errors='coerce').fillna(0)

    # 6. Dinâmica de Tabela (Pivot)
    # Transforma as linhas Green, Blue e Grey em colunas
    df_clean = df.pivot_table(
        index='Produto',
        columns='Tipo_Agua',
        values='Valor',
        aggfunc='first'
    ).reset_index()

    # 7. Formatação Final
    df_clean.columns.name = None # Remove o nome do índice do pivot

    # Garante que todas as colunas existam mesmo se faltar algum dado
    for cor in ['Green', 'Blue', 'Grey']:
        if cor not in df_clean.columns:
            df_clean[cor] = 0.0

    df_clean = df_clean.rename(columns={
        'Produto': 'Produto_EN',
        'Green': 'Agua_Verde',
        'Blue': 'Agua_Azul',
        'Grey': 'Agua_Cinza'
    })

    # Cria a coluna final de totalização
    df_clean['Agua_Total_m3_t'] = df_clean['Agua_Verde'] + df_clean['Agua_Azul'] + df_clean['Agua_Cinza']

    print(f"Sucesso! {len(df_clean)} produtos extraídos.")
    return df_clean[['Produto_EN', 'Agua_Verde', 'Agua_Azul', 'Agua_Cinza', 'Agua_Total_m3_t']]

# ==========================================
# COMO EXECUTAR (Ajuste os índices abaixo)
# ==========================================

try:
    df_animais = limpar_planilha_wfn(
        caminho_arquivo='Report48-Appendix-V.xlsx', # Nome do seu arquivo baixado
        linha_inicio=4,       # Pula as primeiras 4 linhas de cabeçalho bagunçado
        col_produto=2,        # Índice da coluna com o nome do produto
        col_tipo_agua=8,      # Índice da coluna que tem as palavras Green/Blue/Grey
        col_valor_alvo=12     # Índice da coluna com os valores (ex: Média Global)
    )

    # Exporta o resultado limpo
    df_animais.to_excel('waterstat_animais_limpo.xlsx', index=False)
    print("\nVisualização dos dados limpos:")
    print(df_animais.head())

except Exception as e:
    print(f"Erro ao processar: {e}")

import pandas as pd

def limpar_planilha_vegetais(caminho_arquivo, linha_inicio, col_produto, col_tipo_agua, col_valor_alvo):
    """
    Função dedicada para limpar o Apêndice II (Report 47) da Water Footprint Network.
    """
    print(f"Lendo o arquivo: {caminho_arquivo}...")

    # Carrega o Excel ignorando o cabeçalho complexo
    df_raw = pd.read_excel(caminho_arquivo, header=None, skiprows=linha_inicio)

    # Filtra apenas as 3 colunas necessárias
    df = df_raw[[col_produto, col_tipo_agua, col_valor_alvo]].copy()
    df.columns = ['Produto', 'Tipo_Agua', 'Valor']

    # Limpeza de espaços em branco e padronização
    df['Tipo_Agua'] = df['Tipo_Agua'].astype(str).str.strip().str.capitalize()
    df['Produto'] = df['Produto'].astype(str).str.strip()

    # Substitui células que o Pandas leu como 'nan' por valores nulos reais
    df.loc[df['Produto'] == 'nan', 'Produto'] = None
    df.loc[df['Produto'] == '', 'Produto'] = None

    # PREENCHIMENTO PARA BAIXO (O segredo para ler essa tabela)
    # Copia o nome do alimento (ex: Wheat) para as linhas do Blue e Grey
    df['Produto'] = df['Produto'].ffill()

    # Mantém apenas as linhas que informam a cor da água
    df = df[df['Tipo_Agua'].isin(['Green', 'Blue', 'Grey'])]

    # Converte os valores para números (erros ou hífens viram zero)
    df['Valor'] = pd.to_numeric(df['Valor'], errors='coerce').fillna(0)

    # Transforma as cores da água em colunas (Pivot)
    df_clean = df.pivot_table(
        index='Produto',
        columns='Tipo_Agua',
        values='Valor',
        aggfunc='first'
    ).reset_index()

    df_clean.columns.name = None # Limpa o nome do índice

    # Garante que as três colunas de água existam
    for cor in ['Green', 'Blue', 'Grey']:
        if cor not in df_clean.columns:
            df_clean[cor] = 0.0

    # Renomeia para o padrão que o nosso script principal (Rapidfuzz) exige
    df_clean = df_clean.rename(columns={
        'Produto': 'Produto_EN',
        'Green': 'Agua_Verde',
        'Blue': 'Agua_Azul',
        'Grey': 'Agua_Cinza'
    })

    # Calcula a Pegada Hídrica Total
    df_clean['Agua_Total_m3_t'] = df_clean['Agua_Verde'] + df_clean['Agua_Azul'] + df_clean['Agua_Cinza']

    print(f"Sucesso! {len(df_clean)} matrizes vegetais extraídas.")
    return df_clean[['Produto_EN', 'Agua_Verde', 'Agua_Azul', 'Agua_Cinza', 'Agua_Total_m3_t']]


# ==========================================
# EXECUÇÃO PARA O REPORT 47 (VEGETAIS) - MÉDIA GLOBAL
# ==========================================
try:
    df_vegetais = limpar_planilha_vegetais(
        caminho_arquivo='Report47-Appendix-II.xlsx',
        linha_inicio=6,       # Pula as 6 linhas de cabeçalho. O dado começa na 7ª linha do Excel
        col_produto=4,        # Coluna E: Nome curto (Product description FAOSTAT)
        col_tipo_agua=8,      # Coluna I: WF type (Green/Blue/Grey)
        col_valor_alvo=9      # Coluna J: Global average (Média Mundial)
    )

    # Exporta para ser usado na etapa final do artigo
    df_vegetais.to_excel('waterstat_vegetais_global_limpo.xlsx', index=False)
    print("\nVisualização dos primeiros dados limpos:")
    print(df_vegetais.head())

except Exception as e:
    print(f"Erro na extração: {e}")

!pip install deep_translator

import pandas as pd
from deep_translator import GoogleTranslator
from tqdm import tqdm

tqdm.pandas(desc="Traduzindo a TACO para o Inglês")

def preparar_taco(caminho_arquivo_entrada, caminho_arquivo_saida):
    print("Carregando a base da TACO...")
    df = pd.read_excel(caminho_arquivo_entrada)

    # ==========================================
    # O FIX INDESTRUTÍVEL (BUSCA DINÂMICA + POSIÇÃO)
    # ==========================================
    col_nome = None
    col_prot = None

    # 1. Tenta achar pelo nome (mesmo que esteja escrito apenas "alimento" ou "Proteína")
    for col in df.columns:
        if 'alimento' in str(col).lower() or 'descri' in str(col).lower():
            col_nome = col
        if 'rote' in str(col).lower(): # Pega "Proteína", "Proteina", "proteina"
            col_prot = col

    # 2. Se o cabeçalho estiver tão destruído que não achou as palavras, apela para a posição!
    # Na TACO padrão, a coluna 1 (2ª coluna) é o nome e a coluna 5 (6ª coluna) é a proteína.
    if not col_nome:
        col_nome = df.columns[1]
    if not col_prot:
        col_prot = df.columns[5]

    print(f"-> Coluna identificada para o NOME: '{col_nome}'")
    print(f"-> Coluna identificada para a PROTEÍNA: '{col_prot}'")

    # Renomeia as colunas com segurança
    df = df.rename(columns={
        col_nome: 'Produto_PT',
        col_prot: 'Proteina_g'
    })

    # ==========================================
    # CONTINUAÇÃO DO PROCESSAMENTO
    # ==========================================
    # Converte vírgula para ponto e transforma textos (como "Tr" de traços) em nulo
    if df['Proteina_g'].dtype == object:
        df['Proteina_g'] = df['Proteina_g'].astype(str).str.replace(',', '.')
        df['Proteina_g'] = pd.to_numeric(df['Proteina_g'], errors='coerce')

    # Aplica a regra da Anvisa (>= 6g)
    df_fonte_proteina = df[df['Proteina_g'] >= 6.0].copy()
    print(f"\nAlimentos que são fonte de proteína (>=6g) encontrados: {len(df_fonte_proteina)}")

    # Inicia a tradução
    tradutor = GoogleTranslator(source='pt', target='en')

    df_fonte_proteina['Produto_EN'] = df_fonte_proteina['Produto_PT'].progress_apply(
        lambda texto: tradutor.translate(str(texto)) if pd.notna(texto) else None
    )

    # Injeta a coluna para a tabela DIAAS
    df_fonte_proteina['Categoria_Alimento'] = ""

    # Organiza a saída
    colunas_finais = ['Produto_PT', 'Produto_EN', 'Categoria_Alimento', 'Proteina_g']
    outras_colunas = [col for col in df_fonte_proteina.columns if col not in colunas_finais]

    df_final = df_fonte_proteina[colunas_finais + outras_colunas]

    # Salva o arquivo final
    df_final.to_excel(caminho_arquivo_saida, index=False)
    print(f"\nSucesso! Arquivo salvo como: {caminho_arquivo_saida}")

# Execução
try:
    preparar_taco('taco.xlsx', 'taco_traduzida.xlsx')
except Exception as e:
    print(f"Ocorreu um erro crítico: {e}")

!pip install rapidfuzz

!pip install rapidfuzz

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util
import torch

# ================================
# 1. CARREGAR OS ARQUIVOS EXCEL E LIMPAR
# ================================
print("Carregando bases de dados...")
taco = pd.read_excel('taco_traduzida.xlsx')
diaas = pd.read_excel('Tabela DIAAS.xlsx')
wf_animais = pd.read_excel('waterstat_animais_limpo.xlsx')
wf_vegetais = pd.read_excel('waterstat_vegetais_limpo.xlsx')

pegada_global = pd.concat([wf_animais, wf_vegetais], ignore_index=True).dropna(subset=['Produto_EN'])
pegada_choices = pegada_global['Produto_EN'].tolist()

taco['Produto_EN'] = taco['Produto_EN'].fillna("").astype(str)
taco['Produto_PT_limpo'] = taco['Produto_PT'].fillna("").astype(str).str.lower()

# ================================
# 2. ANCORAGEM OBRIGATÓRIA (REGRAS RÍGIDAS)
# ================================
# Dicionário mapeando a palavra em PT para a Categoria Mãe exata da WFN
regras_ouro = {
    'carne, bovina': 'Bovine cuts boneless, fresh or chilled',
    'hamburguer': 'Bovine cuts boneless, fresh or chilled',
    'linguica, frango': 'Meat of fowls of the species Gallus domesticus', # Tem que vir antes da regra de 'frango' e 'linguica' geral
    'frango': 'Meat of fowls of the species Gallus domesticus',
    'peru': 'Turkey meat and meat offal prepared or preserved, excluding livers',
    'porco': 'Hams, shoulders and cuts thereof, of swine bone in, fresh or chilled',
    'linguica': 'Swine meat cured, nes',
    'presunto': 'Swine meat cured, nes',
    'leite, de vaca, desnatado': 'Milk powder not exceeding 1.5% fat',
    'leite, de vaca, integral': 'Milk and cream not concentrated and unsweetened exceeding 6% fat',
    'leite, condensado': 'Milk and cream nes sweetened',
    'queijo': 'Cheese nes',
    'ovo': 'Eggs, bird, in shell, fresh, preserved or cooked',
    'arroz': 'Rice, paddy',
    'feijao': 'Beans, dry',
    'trigo': 'Wheat',
    'macarrao': 'Wheat',
    'pao': 'Wheat',
    'aveia': 'Oats',
    'milho': 'Maize',
    'soja': 'Soybeans'
}

print("Aplicando ancoragem rígida para carnes e grãos base...")
taco['Match_WF_Rigido'] = None

for i, row in taco.iterrows():
    nome_pt = row['Produto_PT_limpo']
    for chave_pt, valor_wfn in regras_ouro.items():
        if chave_pt in nome_pt:
            taco.at[i, 'Match_WF_Rigido'] = valor_wfn
            break # Achou a regra, para de procurar

# ================================
# 3. VETORIZAÇÃO SEMÂNTICA (Apenas para os "difíceis")
# ================================
print("Carregando o modelo de IA para analisar os alimentos restantes...")
modelo = SentenceTransformer('all-MiniLM-L6-v2')
embeddings_wfn = modelo.encode(pegada_choices, convert_to_tensor=True)

print("Calculando IA Semântica...")
for i, row in taco.iterrows():
    # Se já foi resolvido pela regra rígida, pula o cálculo da IA e dá Score 100%
    if pd.notna(row['Match_WF_Rigido']):
        taco.at[i, 'Match_Final_WFN'] = row['Match_WF_Rigido']
        taco.at[i, 'Score_Confianca'] = 100.0
    else:
        # Se não tem regra, a IA vetorial entra em ação
        embedding_query = modelo.encode(row['Produto_EN'], convert_to_tensor=True)
        cos_score = util.cos_sim(embedding_query, embeddings_wfn)[0]

        melhor_idx = torch.argmax(cos_score).item()
        melhor_score = cos_score[melhor_idx].item() * 100

        taco.at[i, 'Match_Final_WFN'] = pegada_choices[melhor_idx]
        taco.at[i, 'Score_Confianca'] = round(melhor_score, 2)

# ================================
# 4. EXPORTAR TABELA DE REVISÃO E APLICAR MATCH DE PESCADOS
# ================================
# Limpa Pescados que a IA tentou adivinhar (Pescados não têm pegada hídrica medida pela WFN)
palavras_peixe = ['pescada', 'salmao', 'sardinha', 'lambari', 'abadejo', 'atum', 'bacalhau', 'cacao', 'camarao', 'caranguejo', 'corimba', 'corvina', 'dourada', 'manjuba', 'merluza', 'pintado', 'porquinho', 'tucunare']
for i, row in taco.iterrows():
    if any(peixe in row['Produto_PT_limpo'] for peixe in palavras_peixe):
        taco.at[i, 'Match_Final_WFN'] = None
        taco.at[i, 'Score_Confianca'] = 0.0

correspondencias = taco[['Produto_PT', 'Produto_EN', 'Match_Final_WFN', 'Score_Confianca']].sort_values(by='Score_Confianca', ascending=True)
correspondencias.to_excel('1_revisao_hibrida.xlsx', index=False)
print("Tabela de revisão gerada: '1_revisao_hibrida.xlsx'")

# ================================
# 5. MERGE MÚLTIPLO: TACO + PEGADA + DIAAS
# ================================
print("Realizando os cruzamentos de dados finais...")
df = pd.merge(taco, pegada_global, left_on='Match_Final_WFN', right_on='Produto_EN', how='inner')

df['Categoria_Alimento'] = df['Categoria_Alimento'].astype(str).str.strip()
diaas['Categoria_Alimento'] = diaas['Categoria_Alimento'].astype(str).str.strip()
df = pd.merge(df, diaas, on='Categoria_Alimento', how='left')
df['DIAAS'] = pd.to_numeric(df['DIAAS'], errors='coerce').fillna(50.0)

# ================================
# 6. CÁLCULO DAS EFICIÊNCIAS E EXPORTAÇÃO
# ================================
df['Proteina_g'] = pd.to_numeric(df['Proteina_g'], errors='coerce')
df['Agua_Total_m3_t'] = pd.to_numeric(df['Agua_Total_m3_t'], errors='coerce')
df = df.dropna(subset=['Proteina_g', 'Agua_Total_m3_t'])

df['Eficiencia_Bruta_g_m3'] = df['Proteina_g'] / df['Agua_Total_m3_t']
df['Proteina_Digestivel_g'] = df['Proteina_g'] * (df['DIAAS'] / 100)
df['Eficiencia_Real_g_m3'] = df['Proteina_Digestivel_g'] / df['Agua_Total_m3_t']

colunas_finais = [
    'Produto_PT', 'Match_Final_WFN', 'Score_Confianca', 'Categoria_Alimento',
    'Proteina_g', 'DIAAS', 'Proteina_Digestivel_g',
    'Agua_Verde', 'Agua_Azul', 'Agua_Cinza', 'Agua_Total_m3_t',
    'Eficiencia_Bruta_g_m3', 'Eficiencia_Real_g_m3'
]

df_final = df[colunas_finais].sort_values(by='Eficiencia_Real_g_m3', ascending=False)
df_final.to_excel('2_eficiencia_proteica_real_hibrida.xlsx', index=False)
print(f"\nSucesso! Arquivo final gerado: '2_eficiencia_proteica_real_hibrida.xlsx'")

!pip install adjustText

# ============================================================
# DPWEI - Figure Generation
# Google Colab
# ============================================================

# Uncomment if running for the first time
# !pip install adjustText openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from adjustText import adjust_text

from google.colab import files

# ------------------------------------------------------------
# Matplotlib configuration
# ------------------------------------------------------------

plt.rcParams["figure.dpi"] = 300
plt.rcParams["savefig.dpi"] = 300

plt.rcParams["font.family"] = "DejaVu Sans"

plt.rcParams["font.size"] = 11
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 12
plt.rcParams["xtick.labelsize"] = 10
plt.rcParams["ytick.labelsize"] = 10
plt.rcParams["legend.fontsize"] = 10

plt.rcParams["axes.spines.top"] = False
plt.rcParams["axes.spines.right"] = False

# ------------------------------------------------------------
# Color palette
# ------------------------------------------------------------

COLOR_DPWEI = "#1f4e79"

COLOR_GREEN = "#4CAF50"
COLOR_BLUE  = "#2196F3"
COLOR_GRAY  = "#9E9E9E"

COLOR_WATER = "#4F81BD"
COLOR_PROTEIN = "#C0504D"

print("Configuration loaded.")

# ============================================================
# Upload Excel file
# ============================================================

uploaded = files.upload()

filename = next(iter(uploaded))

df = pd.read_excel(filename)

# ============================================================
# Convert numeric columns
# ============================================================

numeric_columns = [
    "Proteina_Digestivel_g",
    "Agua_Total_m3_t",
    "Agua_Verde",
    "Agua_Azul",
    "Agua_Cinza",
    "%_Agua_Verde",
    "%_Agua_Azul",
    "%_Agua_Cinza"
]

for col in numeric_columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

# ============================================================
# Rename columns
# ============================================================

df = df.rename(columns={"Inglês": "Product"})

# ============================================================
# Calculate DPWEI
# ============================================================

df["DPWEI"] = (
    df["Proteina_Digestivel_g"] /
    df["Agua_Total_m3_t"]
) * 1000

# ============================================================
# Sort by DPWEI
# ============================================================

df = (
    df
    .sort_values("DPWEI", ascending=False)
    .reset_index(drop=True)
)

top10 = df.head(10).copy()

print(f"Number of foods: {len(df)}")
display(df[["Product", "DPWEI"]].head(10))

# ============================================================
# Figure 1 - Top 10 Foods Ranked by DPWEI
# ============================================================

ranking = (
    top10
    .sort_values("DPWEI", ascending=True)
    .reset_index(drop=True)
)

# Create labels with ranking
labels = [
    f"{10-i}. {product}"
    for i, product in enumerate(ranking["Product"])
]

# ============================================================
# Figure 1 - Top 10 Foods Ranked by DPWEI Score
# ============================================================

from matplotlib.ticker import MaxNLocator

# ------------------------------------------------------------
# Prepare data
# ------------------------------------------------------------

ranking = (
    df.sort_values("DPWEI", ascending=False)
      .head(10)
      .reset_index(drop=True)
)

labels = ranking["Product"].tolist()

# ------------------------------------------------------------
# Color palette (ColorBrewer Blues)
# ------------------------------------------------------------

colors = [
    "#08306B",  # 1st
    "#2171B5",  # 2nd
    "#6BAED6",  # 3rd
]

colors.extend(["#C6DBEF"] * (len(ranking) - 3))

# ------------------------------------------------------------
# Create figure
# ------------------------------------------------------------

fig, ax = plt.subplots(figsize=(11, 6.2))

bars = ax.barh(
    y=labels,
    width=ranking["DPWEI"],
    color=colors,
    height=0.70,
    linewidth=0
)

# Highest score at the top
ax.invert_yaxis()

# ------------------------------------------------------------
# Add score labels
# ------------------------------------------------------------

offset = ranking["DPWEI"].max() * 0.02

for bar, score in zip(bars, ranking["DPWEI"]):

    ax.text(
        score + offset,
        bar.get_y() + bar.get_height() / 2,
        f"{score:.2f}",
        va="center",
        ha="left",
        fontsize=10,
        fontweight="bold",
        color="#333333"
    )

# ------------------------------------------------------------
# Axis formatting
# ------------------------------------------------------------

ax.set_xlabel(
    "DPWEI Score",
    fontsize=12,
    fontweight="bold"
)

ax.set_ylabel("")

ax.set_xlim(
    0,
    ranking["DPWEI"].max() * 1.22
)

ax.xaxis.set_major_locator(MaxNLocator(7))

# ------------------------------------------------------------
# Grid
# ------------------------------------------------------------

ax.grid(
    axis="x",
    linestyle="--",
    linewidth=0.6,
    alpha=0.30
)

ax.set_axisbelow(True)

# ------------------------------------------------------------
# Tick formatting
# ------------------------------------------------------------

ax.tick_params(
    axis="x",
    labelsize=10
)

ax.tick_params(
    axis="y",
    labelsize=10.5,
    length=0
)

# ------------------------------------------------------------
# Remove unnecessary spines
# ------------------------------------------------------------

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_visible(False)
ax.spines["bottom"].set_linewidth(0.8)

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

plt.tight_layout()

# ------------------------------------------------------------
# Export
# ------------------------------------------------------------

plt.savefig(
    "Figure1_DPWEI_Ranking.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    "Figure1_DPWEI_Ranking.pdf",
    bbox_inches="tight"
)

plt.savefig(
    "Figure1_DPWEI_Ranking.svg",
    bbox_inches="tight"
)

plt.show()

# ============================================================
# Figure 2 - Relationship between Digestible Protein,
# Total Water Footprint and DPWEI Score
# ============================================================

from adjustText import adjust_text

# ------------------------------------------------------------
# Prepare data
# ------------------------------------------------------------

ranking = (
    df.sort_values("DPWEI", ascending=False)
      .head(10)
      .reset_index(drop=True)
)

# ------------------------------------------------------------
# Create figure
# ------------------------------------------------------------

fig, ax = plt.subplots(figsize=(10.5, 7.5))

scatter = ax.scatter(
    ranking["Agua_Total_m3_t"],
    ranking["Proteina_Digestivel_g"],
    c=ranking["DPWEI"],
    cmap="viridis",
    s=130,
    edgecolors="white",
    linewidths=0.8,
    alpha=0.95,
    zorder=3
)

# ------------------------------------------------------------
# Add labels
# ------------------------------------------------------------

texts = []

for _, row in ranking.iterrows():

    texts.append(
        ax.text(
            row["Agua_Total_m3_t"],
            row["Proteina_Digestivel_g"],
            row["Product"],
            fontsize=9,
            ha="center",
            va="center",
            bbox=dict(
                facecolor="white",
                edgecolor="none",
                alpha=0.85,
                pad=0.30
            ),
            zorder=5
        )
    )

adjust_text(
    texts,
    x=ranking["Agua_Total_m3_t"],
    y=ranking["Proteina_Digestivel_g"],
    ax=ax,

    expand=(2.5, 2.5),
    force_text=(2.5, 2.5),
    force_static=(2.0, 2.0),
    force_pull=(0.15, 0.15),

    avoid_self=True,
    prevent_crossings=True,
    ensure_inside_axes=True,

    only_move={
        "text": "xy",
        "static": "xy",
        "explode": "xy",
        "pull": "xy",
    },

    arrowprops=dict(
        arrowstyle="-",
        color="gray",
        lw=0.6,
        alpha=0.7,
        shrinkA=3,
        shrinkB=3,
    )
)

# ------------------------------------------------------------
# Colorbar
# ------------------------------------------------------------

cbar = plt.colorbar(
    scatter,
    ax=ax,
    pad=0.02
)

cbar.set_label(
    "DPWEI Score",
    fontsize=11,
    fontweight="bold"
)

cbar.ax.tick_params(labelsize=10)

# ------------------------------------------------------------
# Axis labels
# ------------------------------------------------------------

ax.set_xlabel(
    "Total Water Footprint (m³/t)",
    fontsize=12,
    fontweight="bold"
)

ax.set_ylabel(
    "Digestible Protein (g/100 g)",
    fontsize=12,
    fontweight="bold"
)

# ------------------------------------------------------------
# Improve limits
# ------------------------------------------------------------

x_min = ranking["Agua_Total_m3_t"].min()
x_max = ranking["Agua_Total_m3_t"].max()

y_min = ranking["Proteina_Digestivel_g"].min()
y_max = ranking["Proteina_Digestivel_g"].max()

x_margin = (x_max - x_min) * 0.08
y_margin = (y_max - y_min) * 0.08

ax.set_xlim(
    x_min - x_margin,
    x_max + x_margin
)

ax.set_ylim(
    y_min - y_margin,
    y_max + y_margin
)

# ------------------------------------------------------------
# Grid
# ------------------------------------------------------------

ax.grid(
    linestyle="--",
    linewidth=0.6,
    alpha=0.30
)

ax.set_axisbelow(True)

# ------------------------------------------------------------
# Tick formatting
# ------------------------------------------------------------

ax.tick_params(
    axis="both",
    labelsize=10
)

# ------------------------------------------------------------
# Remove unnecessary spines
# ------------------------------------------------------------

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

plt.tight_layout()

# ------------------------------------------------------------
# Export
# ------------------------------------------------------------

plt.savefig(
    "Figure2_DigestibleProtein_vs_TotalWaterFootprint.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    "Figure2_DigestibleProtein_vs_TotalWaterFootprint.pdf",
    bbox_inches="tight"
)

plt.savefig(
    "Figure2_DigestibleProtein_vs_TotalWaterFootprint.svg",
    bbox_inches="tight"
)

plt.show()

# ============================================================
# Figure 3 - Composition of the Total Water Footprint
# (Top 10 Foods by DPWEI Score)
# ============================================================

# ------------------------------------------------------------
# Prepare data
# ------------------------------------------------------------

ranking = (
    df.sort_values("DPWEI", ascending=False)
      .head(10)
      .copy()
)

# Reverse order so the highest DPWEI appears at the top
ranking = ranking.iloc[::-1]

# ------------------------------------------------------------
# Create figure
# ------------------------------------------------------------

fig, ax = plt.subplots(figsize=(10.5, 7.5))

# ------------------------------------------------------------
# Colors
# ------------------------------------------------------------

green_color = "#4CAF50"
blue_color = "#4F81BD"
gray_color = "#9E9E9E"

# ------------------------------------------------------------
# Horizontal stacked bars
# ------------------------------------------------------------

ax.barh(
    ranking["Product"],
    ranking["Agua_Verde"],
    color=green_color,
    edgecolor="white",
    linewidth=0.6,
    label="Green Water"
)

ax.barh(
    ranking["Product"],
    ranking["Agua_Azul"],
    left=ranking["Agua_Verde"],
    color=blue_color,
    edgecolor="white",
    linewidth=0.6,
    label="Blue Water"
)

ax.barh(
    ranking["Product"],
    ranking["Agua_Cinza"],
    left=ranking["Agua_Verde"] + ranking["Agua_Azul"],
    color=gray_color,
    edgecolor="white",
    linewidth=0.6,
    label="Gray Water"
)

# ------------------------------------------------------------
# Axis labels
# ------------------------------------------------------------

ax.set_xlabel(
    "Total Water Footprint (m³/t)",
    fontsize=12,
    fontweight="bold"
)

ax.set_ylabel("")

# ------------------------------------------------------------
# Legend
# ------------------------------------------------------------

ax.legend(
    loc="upper center",
    bbox_to_anchor=(0.5, 1.08),
    ncol=3,
    frameon=False,
    fontsize=10
)

# ------------------------------------------------------------
# Grid
# ------------------------------------------------------------

ax.grid(
    axis="x",
    linestyle="--",
    linewidth=0.6,
    alpha=0.30
)

ax.set_axisbelow(True)

# ------------------------------------------------------------
# Tick formatting
# ------------------------------------------------------------

ax.tick_params(
    axis="x",
    labelsize=10
)

ax.tick_params(
    axis="y",
    labelsize=10
)

# ------------------------------------------------------------
# Remove unnecessary spines
# ------------------------------------------------------------

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

plt.tight_layout()

# ------------------------------------------------------------
# Export
# ------------------------------------------------------------

plt.savefig(
    "Figure3_WaterFootprintComposition.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    "Figure3_WaterFootprintComposition.pdf",
    bbox_inches="tight"
)

plt.savefig(
    "Figure3_WaterFootprintComposition.svg",
    bbox_inches="tight"
)

plt.show()

# ============================================================
# Figure 4 - Gray Water Footprint of Food Products
# ============================================================

# ------------------------------------------------------------
# Prepare data
# ------------------------------------------------------------

ranking = (
    df.sort_values("Agua_Cinza", ascending=False)
      .copy()
)

# Reverse order so the largest value appears at the top
ranking = ranking.iloc[::-1]

# ------------------------------------------------------------
# Create figure
# ------------------------------------------------------------

fig, ax = plt.subplots(figsize=(10.5, 8))

# ------------------------------------------------------------
# Color
# ------------------------------------------------------------

gray_color = "#7F7F7F"

# ------------------------------------------------------------
# Horizontal bars
# ------------------------------------------------------------

bars = ax.barh(
    ranking["Product"],
    ranking["Agua_Cinza"],
    color=gray_color,
    edgecolor="white",
    linewidth=0.6
)

# ------------------------------------------------------------
# Add values
# ------------------------------------------------------------

max_value = ranking["Agua_Cinza"].max()

offset = max_value * 0.01

for bar in bars:

    width = bar.get_width()

    ax.text(
        width + offset,
        bar.get_y() + bar.get_height()/2,
        f"{width:,.0f}",
        va="center",
        ha="left",
        fontsize=9
    )

# ------------------------------------------------------------
# Axis labels
# ------------------------------------------------------------

ax.set_xlabel(
    "Gray Water Footprint (m³/t)",
    fontsize=12,
    fontweight="bold"
)

ax.set_ylabel("")

# ------------------------------------------------------------
# Grid
# ------------------------------------------------------------

ax.grid(
    axis="x",
    linestyle="--",
    linewidth=0.6,
    alpha=0.30
)

ax.set_axisbelow(True)

# ------------------------------------------------------------
# Tick formatting
# ------------------------------------------------------------

ax.tick_params(
    axis="x",
    labelsize=10
)

ax.tick_params(
    axis="y",
    labelsize=10
)

# ------------------------------------------------------------
# Remove unnecessary spines
# ------------------------------------------------------------

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# ------------------------------------------------------------
# Improve limits
# ------------------------------------------------------------

ax.set_xlim(
    0,
    max_value * 1.10
)

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

plt.tight_layout()

# ------------------------------------------------------------
# Export
# ------------------------------------------------------------

plt.savefig(
    "Figure4_GrayWaterFootprint.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    "Figure4_GrayWaterFootprint.pdf",
    bbox_inches="tight"
)

plt.savefig(
    "Figure4_GrayWaterFootprint.svg",
    bbox_inches="tight"
)

plt.show()

